name: chirp_polly
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  firebase_core: ^3.8.1
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/parrot_transparent.png
    - assets/legal/
    - assets/data/curriculum/es_a1/es_a1_m01.json
    - assets/data/curriculum/es_a1/es_a1_m02.json
    - assets/data/curriculum/es_a1/es_a1_m03.json
    - assets/data/curriculum/es_a1/es_a1_m04.json
    - assets/data/curriculum/es_a1/es_a1_m05.json
    - assets/data/curriculum/es_a1/es_a1_m06.json
    - assets/data/curriculum/es_a1/es_a1_m07.json
    - assets/data/curriculum/es_a1/es_a1_m08.json
    - assets/data/curriculum/es_a1/es_a1_m09.json
    - assets/data/curriculum/es_a1/es_a1_m10.json
    - assets/data/curriculum/es_a2/es_a2_m01.json
    - assets/data/curriculum/es_a2/es_a2_m02.json
    - assets/data/curriculum/es_a2/es_a2_m03.json
    - assets/data/curriculum/es_a2/es_a2_m04.json
    - assets/data/curriculum/es_a2/es_a2_m05.json
    - assets/data/curriculum/es_a2/es_a2_m06.json
    - assets/data/curriculum/es_a2/es_a2_m07.json
    - assets/data/curriculum/es_a2/es_a2_m08.json
    - assets/data/curriculum/es_a2/es_a2_m09.json
    - assets/data/curriculum/es_a2/es_a2_m10.json
    - assets/data/curriculum/es_b1/es_b1_m01.json
    - assets/data/curriculum/es_b1/es_b1_m02.json
    - assets/data/curriculum/es_b1/es_b1_m03.json
    - assets/data/curriculum/es_b1/es_b1_m04.json
    - assets/data/curriculum/es_b1/es_b1_m05.json
    - assets/data/curriculum/es_b1/es_b1_m06.json
    - assets/data/curriculum/es_b1/es_b1_m07.json
    - assets/data/curriculum/es_b1/es_b1_m08.json
    - assets/data/curriculum/es_b1/es_b1_m09.json
    - assets/data/curriculum/es_b1/es_b1_m10.json
